"""empty message

Revision ID: 2c9c61a68a60
Revises: 5dc3473af2bb
Create Date: 2022-09-13 00:11:32.155304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9c61a68a60'
down_revision = '5dc3473af2bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision__almuerzo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=120), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision__almuerzo')
    # ### end Alembic commands ###
