"""empty message

Revision ID: 989109ca9a30
Revises: 9ef322ffd21e
Create Date: 2022-09-04 23:06:29.460646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989109ca9a30'
down_revision = '9ef322ffd21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('dia', sa.String(length=180), nullable=False))
    op.add_column('menu', sa.Column('semana_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'menu', ['dia'])
    op.create_foreign_key(None, 'menu', 'semanas', ['semana_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_constraint(None, 'menu', type_='unique')
    op.drop_column('menu', 'semana_id')
    op.drop_column('menu', 'dia')
    # ### end Alembic commands ###
