"""empty message

Revision ID: 9ef322ffd21e
Revises: 
Create Date: 2022-09-04 22:37:48.787993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef322ffd21e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ensalada', sa.String(length=180), nullable=False),
    sa.Column('principal', sa.String(length=180), nullable=False),
    sa.Column('postre', sa.String(length=180), nullable=False),
    sa.Column('bebida', sa.String(length=180), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bebida'),
    sa.UniqueConstraint('ensalada'),
    sa.UniqueConstraint('postre'),
    sa.UniqueConstraint('principal')
    )
    op.create_table('semanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lunes', sa.String(length=80), nullable=True),
    sa.Column('martes', sa.String(length=80), nullable=True),
    sa.Column('miercoles', sa.String(length=80), nullable=True),
    sa.Column('jueves', sa.String(length=80), nullable=True),
    sa.Column('viernes', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jueves'),
    sa.UniqueConstraint('lunes'),
    sa.UniqueConstraint('martes'),
    sa.UniqueConstraint('miercoles'),
    sa.UniqueConstraint('viernes')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('direccion', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('casino_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['casino_id'], ['casino.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('telefono', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('reporte__usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=120), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte__usuario')
    op.drop_table('usuarios')
    op.drop_table('empresa')
    op.drop_table('semanas')
    op.drop_table('menu')
    op.drop_table('casino')
    # ### end Alembic commands ###
