"""empty message

Revision ID: b44e3b08aff4
Revises: f095274a6c18
Create Date: 2022-09-14 05:02:12.221212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44e3b08aff4'
down_revision = 'f095274a6c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisiones', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'decisiones', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decisiones', type_='foreignkey')
    op.drop_column('decisiones', 'usuario_id')
    # ### end Alembic commands ###
