"""empty message

Revision ID: f095274a6c18
Revises: 94caca343859
Create Date: 2022-09-14 05:00:11.788838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f095274a6c18'
down_revision = '94caca343859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usuarios_decision_id_fkey', 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'decision_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('decision_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('usuarios_decision_id_fkey', 'usuarios', 'decisiones', ['decision_id'], ['id'])
    # ### end Alembic commands ###
